"""Render docs/COMPLIANCE.md from the machine-readable sources (config/models.yaml, config/packs/*.yaml).

The licence table is generated, never hand-edited, so it cannot drift from what the code enforces
(a commercial profile refuses models whose licence is not commercial_ok). A unit test fails if the
committed file differs from this script's output.

    python scripts/render_compliance.py            # rewrite docs/COMPLIANCE.md
    python scripts/render_compliance.py --check    # exit 1 if the committed file is stale
"""
import argparse
import sys
from pathlib import Path

from lexis.packs.loader import discover_packs
from lexis.registry.models import ModelRegistry

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "COMPLIANCE.md"


def render() -> str:
    registry = ModelRegistry.from_file(ROOT / "config" / "models.yaml")
    packs = discover_packs(ROOT / "config" / "packs")

    lines = [
        "# Licence and compliance register",
        "",
        "_Generated by `scripts/render_compliance.py` from `config/models.yaml` and `config/packs/*.yaml`. "
        "Do not edit by hand._",
        "",
        "**Verified = the licence was confirmed from a primary page. Unverified entries are recalled/assumed and "
        "must be checked before any commercial or redistributed use** (a commercial profile refuses them).",
        "",
        "## Models",
        "",
        "| Key | Hub id | Kind | Licence | Verified | Commercial use |",
        "|---|---|---|---|---|---|",
    ]
    for key in sorted(registry.keys()):
        s = registry.get(key)
        lines.append(f"| `{key}` | `{s.name}` | {s.kind} | {s.license} | {'yes' if s.license_verified else '**no**'} "
                     f"| {'yes' if s.commercial_ok else '**no**'} |")

    lines += ["", "## Corpora and datasets, by jurisdiction pack", ""]
    for name in sorted(packs):
        pack = packs[name]
        lines += [f"### `{name}`", "", "| Source | Obligation | Blocks redistribution | Blocks commercial use |", "|---|---|---|---|"]
        for c in pack.compliance:
            lines.append(f"| {c.source} | {c.requirement} | {'**yes**' if c.blocks_redistribution else 'no'} "
                         f"| {'**yes**' if c.blocks_commercial_use else 'no'} |")
        lines.append("")
    lines += [
        "## Notes",
        "",
        "- Non-commercial datasets (e.g. IL-TUR, AILQA) are evaluation-only: never redistributed and never shipped in a demo.",
        "- Only the `us_contracts` pack has been evaluated end to end (CUAD). Other packs are configuration.",
        "- LLM provider terms (Gemini API) apply to any text sent to the generator; do not send confidential documents "
        "to a free-tier endpoint.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print("docs/COMPLIANCE.md is stale; run: python scripts/render_compliance.py")
            sys.exit(1)
        print("docs/COMPLIANCE.md is up to date.")
    else:
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUT}")
